/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.curriculo;

/**
 *
 * @author 182310022
 */
public class currastemplate extends javax.swing.JPanel {
    public static String[] ano = new String[2024];
    /**
     * Creates new form currastemplate
     */
    public currastemplate() {
        initComponents();
        calendario();
        //System.out.println(ano);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        informacoespessoaistab = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        fotoloader = new javax.swing.JLabel();
        nomelb = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        sobrenomelb = new javax.swing.JLabel();
        sobrenome = new javax.swing.JTextField();
        enderecolb = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        cidadelb = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        estadolb = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        ceplb = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        telefonelb = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        emaillb = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        datadenascimentolb = new javax.swing.JLabel();
        datadenascimento = new javax.swing.JTextField();
        nacionalidadelb = new javax.swing.JLabel();
        nacionalidade = new javax.swing.JTextField();
        estadocivillb = new javax.swing.JLabel();
        estadocivil = new javax.swing.JComboBox<>();
        cnhlb = new javax.swing.JLabel();
        cnh = new javax.swing.JTextField();
        escolaridadetab = new javax.swing.JPanel();
        instituicaodeensinolb = new javax.swing.JLabel();
        instituicao = new javax.swing.JTextField();
        localinstituicaolb = new javax.swing.JLabel();
        instituicaoEndereco = new javax.swing.JTextField();
        diplomalb = new javax.swing.JLabel();
        diploma = new javax.swing.JTextField();
        campodeestudolb = new javax.swing.JLabel();
        campodeestudo = new javax.swing.JTextField();
        situacaolb = new javax.swing.JLabel();
        situacao = new javax.swing.JTextField();
        datadeiniciotab2lb = new javax.swing.JLabel();
        mesinicio = new javax.swing.JComboBox<>();
        anoiniciotab2 = new javax.swing.JComboBox<>();
        datadeterminotab2lb = new javax.swing.JLabel();
        mestermino = new javax.swing.JComboBox<>();
        anoterminotab2 = new javax.swing.JComboBox<>();
        experienciatab = new javax.swing.JPanel();
        titulodocargolb = new javax.swing.JLabel();
        titulodocargo = new javax.swing.JTextField();
        empregadorlb = new javax.swing.JLabel();
        empregador = new javax.swing.JTextField();
        cidadetab3lb = new javax.swing.JLabel();
        cidadetab3 = new javax.swing.JTextField();
        estadotab3lb = new javax.swing.JLabel();
        estadotab3 = new javax.swing.JTextField();
        datadeiniciotab3lb = new javax.swing.JLabel();
        datadeiniciotab3 = new javax.swing.JTextField();
        datadeterminotab3lb = new javax.swing.JLabel();
        datadeterminotab3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();

        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/resources/user.png"))); // NOI18N
        foto.setText("jLabel1");

        fotoloader.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fotoloader.setForeground(new java.awt.Color(0, 102, 204));
        fotoloader.setText("+ Carregar foto");

        nomelb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nomelb.setForeground(new java.awt.Color(0, 102, 204));
        nomelb.setText("NOME");

        sobrenomelb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sobrenomelb.setForeground(new java.awt.Color(0, 102, 204));
        sobrenomelb.setText("SOBRENOME");

        enderecolb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        enderecolb.setForeground(new java.awt.Color(0, 102, 204));
        enderecolb.setText("ENDEREÇO");

        cidadelb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cidadelb.setForeground(new java.awt.Color(0, 102, 204));
        cidadelb.setText("CIDADE");

        estadolb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        estadolb.setForeground(new java.awt.Color(0, 102, 204));
        estadolb.setText("ESTADO");

        ceplb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ceplb.setForeground(new java.awt.Color(0, 102, 204));
        ceplb.setText("CEP");

        telefonelb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        telefonelb.setForeground(new java.awt.Color(0, 102, 204));
        telefonelb.setText("TELEFONE");

        emaillb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        emaillb.setForeground(new java.awt.Color(0, 102, 204));
        emaillb.setText("E-MAIL");

        datadenascimentolb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        datadenascimentolb.setForeground(new java.awt.Color(0, 102, 204));
        datadenascimentolb.setText("DATA DE NASCIMENTO");

        nacionalidadelb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nacionalidadelb.setForeground(new java.awt.Color(0, 102, 204));
        nacionalidadelb.setText("NACIONALIDADE");

        estadocivillb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        estadocivillb.setForeground(new java.awt.Color(0, 102, 204));
        estadocivillb.setText("ESTADO CIVIL");

        estadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)" }));
        estadocivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadocivilActionPerformed(evt);
            }
        });

        cnhlb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cnhlb.setForeground(new java.awt.Color(0, 102, 204));
        cnhlb.setText("CARTEIRA NACIONAL DE HABILITAÇÃO(CNH)");

        javax.swing.GroupLayout informacoespessoaistabLayout = new javax.swing.GroupLayout(informacoespessoaistab);
        informacoespessoaistab.setLayout(informacoespessoaistabLayout);
        informacoespessoaistabLayout.setHorizontalGroup(
            informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacoespessoaistabLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estadocivillb)
                    .addGroup(informacoespessoaistabLayout.createSequentialGroup()
                        .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidadelb)
                            .addComponent(telefonelb)
                            .addGroup(informacoespessoaistabLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(informacoespessoaistabLayout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(fotoloader)))))
                        .addGap(47, 47, 47)
                        .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enderecolb)
                            .addGroup(informacoespessoaistabLayout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nacionalidadelb)
                                    .addGroup(informacoespessoaistabLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ceplb)))
                                    .addComponent(nacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emaillb)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(endereco)
                            .addGroup(informacoespessoaistabLayout.createSequentialGroup()
                                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomelb))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sobrenomelb)
                                    .addComponent(sobrenome)))))
                    .addComponent(datadenascimentolb)
                    .addGroup(informacoespessoaistabLayout.createSequentialGroup()
                        .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estadolb)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(informacoespessoaistabLayout.createSequentialGroup()
                        .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(estadocivil, 0, 329, Short.MAX_VALUE)
                            .addComponent(datadenascimento))
                        .addGap(47, 47, 47)
                        .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnhlb)
                            .addComponent(cnh, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        informacoespessoaistabLayout.setVerticalGroup(
            informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacoespessoaistabLayout.createSequentialGroup()
                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacoespessoaistabLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomelb)
                            .addComponent(sobrenomelb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(enderecolb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(informacoespessoaistabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fotoloader)))
                .addGap(33, 33, 33)
                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadelb)
                    .addComponent(estadolb)
                    .addComponent(ceplb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonelb)
                    .addComponent(emaillb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nacionalidadelb)
                    .addComponent(datadenascimentolb))
                .addGap(0, 0, 0)
                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datadenascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadocivillb)
                    .addComponent(cnhlb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacoespessoaistabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );

        jTabbedPane2.addTab("Informações Pessoais", informacoespessoaistab);

        instituicaodeensinolb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        instituicaodeensinolb.setForeground(new java.awt.Color(0, 102, 204));
        instituicaodeensinolb.setText("INSTITUIÇÃO DE ENSINO");

        localinstituicaolb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        localinstituicaolb.setForeground(new java.awt.Color(0, 102, 204));
        localinstituicaolb.setText("LOCAL DA INSTITUIÇÃO DE ENSINO");

        diplomalb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        diplomalb.setForeground(new java.awt.Color(0, 102, 204));
        diplomalb.setText("DIPLOMA");

        campodeestudolb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        campodeestudolb.setForeground(new java.awt.Color(0, 102, 204));
        campodeestudolb.setText("CAMPO DE ESTUDO");

        situacaolb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        situacaolb.setForeground(new java.awt.Color(0, 102, 204));
        situacaolb.setText("SITUAÇÃO");

        datadeiniciotab2lb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        datadeiniciotab2lb.setForeground(new java.awt.Color(0, 102, 204));
        datadeiniciotab2lb.setText("DATA DE INICIO");

        mesinicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        anoiniciotab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoiniciotab2ActionPerformed(evt);
            }
        });

        datadeterminotab2lb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        datadeterminotab2lb.setForeground(new java.awt.Color(0, 102, 204));
        datadeterminotab2lb.setText("DATA DE TÉRMINO");

        mestermino.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        mestermino.setModel(mesinicio.getModel());

        anoterminotab2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout escolaridadetabLayout = new javax.swing.GroupLayout(escolaridadetab);
        escolaridadetab.setLayout(escolaridadetabLayout);
        escolaridadetabLayout.setHorizontalGroup(
            escolaridadetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escolaridadetabLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(escolaridadetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instituicaodeensinolb, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diplomalb, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diploma, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(situacao, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(situacaolb, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escolaridadetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(localinstituicaolb, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campodeestudolb, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(escolaridadetabLayout.createSequentialGroup()
                        .addComponent(datadeiniciotab2lb, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(datadeterminotab2lb, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escolaridadetabLayout.createSequentialGroup()
                        .addComponent(mesinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anoiniciotab2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mestermino, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anoterminotab2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campodeestudo)
                    .addComponent(instituicaoEndereco))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        escolaridadetabLayout.setVerticalGroup(
            escolaridadetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escolaridadetabLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(escolaridadetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instituicaodeensinolb)
                    .addComponent(localinstituicaolb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escolaridadetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instituicaoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escolaridadetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diplomalb)
                    .addComponent(campodeestudolb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escolaridadetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diploma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campodeestudo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escolaridadetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(situacaolb)
                    .addComponent(datadeiniciotab2lb)
                    .addComponent(datadeterminotab2lb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escolaridadetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(anoterminotab2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(situacao, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(mesinicio)
                    .addComponent(anoiniciotab2)
                    .addComponent(mestermino))
                .addContainerGap(378, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Escolaridade", escolaridadetab);

        titulodocargolb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        titulodocargolb.setForeground(new java.awt.Color(0, 102, 204));
        titulodocargolb.setText("TÍTULO DO CARGO");

        empregadorlb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        empregadorlb.setForeground(new java.awt.Color(0, 102, 204));
        empregadorlb.setText("EMPREGADOR");

        cidadetab3lb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cidadetab3lb.setForeground(new java.awt.Color(0, 102, 204));
        cidadetab3lb.setText("CIDADE");

        estadotab3lb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        estadotab3lb.setForeground(new java.awt.Color(0, 102, 204));
        estadotab3lb.setText("ESTADO");

        datadeiniciotab3lb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        datadeiniciotab3lb.setForeground(new java.awt.Color(0, 102, 204));
        datadeiniciotab3lb.setText("DATA DE INICIO");

        datadeterminotab3lb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        datadeterminotab3lb.setForeground(new java.awt.Color(0, 102, 204));
        datadeterminotab3lb.setText("DATA DE TÉRMINO");

        javax.swing.GroupLayout experienciatabLayout = new javax.swing.GroupLayout(experienciatab);
        experienciatab.setLayout(experienciatabLayout);
        experienciatabLayout.setHorizontalGroup(
            experienciatabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(experienciatabLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(experienciatabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulodocargolb, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulodocargo, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadetab3lb, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadetab3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datadeiniciotab3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datadeiniciotab3lb, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(experienciatabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empregadorlb, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadotab3lb, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datadeterminotab3lb, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadotab3, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addComponent(empregador)
                    .addComponent(datadeterminotab3))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        experienciatabLayout.setVerticalGroup(
            experienciatabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(experienciatabLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(experienciatabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulodocargolb)
                    .addComponent(empregadorlb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(experienciatabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulodocargo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empregador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(experienciatabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadetab3lb)
                    .addComponent(estadotab3lb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(experienciatabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadetab3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadotab3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(experienciatabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datadeiniciotab3lb)
                    .addComponent(datadeterminotab3lb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(experienciatabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datadeiniciotab3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datadeterminotab3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(378, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Experiência", experienciatab);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Resumo", jPanel4);

        jTabbedPane2.setSelectedIndex(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void estadocivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadocivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadocivilActionPerformed

    private void anoiniciotab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoiniciotab2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoiniciotab2ActionPerformed
    
    public static void calendario(){
            
        int anoatual = 2024;
        for(int i =0;i<2024;i++){
            anoatual = anoatual- 1;
            ano[i] =  Integer.toString(anoatual);
            System.out.println(anoatual);
        }
        for(int i =0;i<10;i++){
           // System.out.println(ano[i]+ "\n");
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> anoiniciotab2;
    private javax.swing.JComboBox<String> anoterminotab2;
    private javax.swing.JTextField campodeestudo;
    private javax.swing.JLabel campodeestudolb;
    private javax.swing.JTextField cep;
    private javax.swing.JLabel ceplb;
    private javax.swing.JTextField cidade;
    private javax.swing.JLabel cidadelb;
    private javax.swing.JTextField cidadetab3;
    private javax.swing.JLabel cidadetab3lb;
    private javax.swing.JTextField cnh;
    private javax.swing.JLabel cnhlb;
    private javax.swing.JLabel datadeiniciotab2lb;
    private javax.swing.JTextField datadeiniciotab3;
    private javax.swing.JLabel datadeiniciotab3lb;
    private javax.swing.JTextField datadenascimento;
    private javax.swing.JLabel datadenascimentolb;
    private javax.swing.JLabel datadeterminotab2lb;
    private javax.swing.JTextField datadeterminotab3;
    private javax.swing.JLabel datadeterminotab3lb;
    private javax.swing.JTextField diploma;
    private javax.swing.JLabel diplomalb;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emaillb;
    private javax.swing.JTextField empregador;
    private javax.swing.JLabel empregadorlb;
    private javax.swing.JTextField endereco;
    private javax.swing.JLabel enderecolb;
    private javax.swing.JPanel escolaridadetab;
    private javax.swing.JTextField estado;
    private javax.swing.JComboBox<String> estadocivil;
    private javax.swing.JLabel estadocivillb;
    private javax.swing.JLabel estadolb;
    private javax.swing.JTextField estadotab3;
    private javax.swing.JLabel estadotab3lb;
    private javax.swing.JPanel experienciatab;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel fotoloader;
    private javax.swing.JPanel informacoespessoaistab;
    private javax.swing.JTextField instituicao;
    private javax.swing.JTextField instituicaoEndereco;
    private javax.swing.JLabel instituicaodeensinolb;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel localinstituicaolb;
    private javax.swing.JComboBox<String> mesinicio;
    private javax.swing.JComboBox<String> mestermino;
    private javax.swing.JTextField nacionalidade;
    private javax.swing.JLabel nacionalidadelb;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomelb;
    private javax.swing.JTextField situacao;
    private javax.swing.JLabel situacaolb;
    private javax.swing.JTextField sobrenome;
    private javax.swing.JLabel sobrenomelb;
    private javax.swing.JTextField telefone;
    private javax.swing.JLabel telefonelb;
    private javax.swing.JTextField titulodocargo;
    private javax.swing.JLabel titulodocargolb;
    // End of variables declaration//GEN-END:variables
}
